version: '3.6'

networks:
  app: {}

services:
  redis:
    restart: always
    image: redis:6.0.8
    ports:
      - 6379:6379
    networks:
      - app
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  zookeeper:
    image: bitnami/zookeeper:3.7.0
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app

  kafka:
    image: bitnami/kafka:2.8.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app

  mafia-lobby:
    image: registry.digitalocean.com/stupwise/mafia-lobby:9d06687
    environment:
      - REDIS_URI=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - redis
      - kafka
    networks:
      - app

  mafia-websocket:
    image: registry.digitalocean.com/stupwise/mafia-websocket:9d06687
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    networks:
      - app